# Generated by Django 3.1.6 on 2021-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_purposesofpremises'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='purpose',
            field=models.ManyToManyField(blank=True, to='rent.PurposesOfPremises', verbose_name='Назначения'),
        ),
    ]
